<% $date = Time.now.strftime('%y-%m-%d_%H:%M') %>
<% dir = "./report/#{$date}" %>
<% Dir.mkdir dir unless File.exists?(dir)%>
<% Dir.mkdir "#{dir}/images" unless File.exists?("#{dir}/images")%>

default: >
  SITE="https://gestion2.urjc.es/movilidadincoming/es/universidad/registro"
  --require source
  --verbose
  --guess
  -f pretty
  -f html
  -o ./report/<%= $date %>/report.html
  -f json
  -o ./report/<%= $date %>/report.json