<% $date = Time.now.strftime('%y-%m-%d_%H:%M') %>
<% dir = "./report/#{$date}" %>
<% Dir.mkdir dir unless File.exists?(dir)%>
<% Dir.mkdir "#{dir}/images" unless File.exists?("#{dir}/images")%>

default: >
  SITE="https://gestion2.urjc.es/movilidadincoming/es/universidad/registro"
  --require source
  --verbose
  --guess

desktop: >
  DEFAULT_URL="http://magritte.urjc.es/practicas"
  WINDOW_SIZE=1220x700
  -t @desktop
  -r source

mobile: >
  DEFAULT_URL="http://magritte.urjc.es/practicas"
  WINDOW_SIZE=768x700
  -t @mobile
  -r source

tablet: >
  DEFAULT_URL="http://magritte.urjc.es/practicas"
  WINDOW_SIZE=400x700
  -t @tablet
  -r source